### ISSUE TITLE
item vs. member in multiplicity constructs

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#145]
The Composite object uses the term 'item' whereas the other two multiplicity constructs use 'member'. Wouldn't it be better to unify those and use either 'item' or 'member' for all three?

**Comment by jjett** [comment]
@iherman I thought it has been suggested that we would drop the Composite object from the model (+1 from me for that) as it is out of scope. So the difference in vocab is likely moot.

**Comment by iherman** [comment]
> @iherman https://github.com/iherman I thought it has been suggested that we would drop the Composite object from the model (+1 from me for that) as it is out of scope. So the difference in vocab is likely moot.

If this is the decision, it is fine with me; I can go either way. It is still part of the latest draft, though...

**Comment by BigBlueHat** [comment]
Per my comment on #92...I remember we'd agreed to drop Composite also. I just don't remember where. :stuck_out_tongue_winking_eye:

**Comment by BigBlueHat** [comment]
But we should take an `editorial`/`editor_action` as a separate issue if so.

**Comment by jjett** [comment]
@BigBlueHat Dropping composite has been proposed. No actual agreement has been reached that I know of. I can see where most of the problems are though. There's a large disconnect between what collections, lists, aggregations are and how we serialize them. Because of serialization and the manner in which text gets parsed there's little use in differentiating between (so-called) unordered lists and ordered lists. The difference in serialization languages such as html is strictly presentational.

IMO all of these issues are out of scope for an annotation standard. We should leave these issues (choice, list, composite, etc.) for other working groups to solve.

**Comment by iherman** [comment]
Closed by resolution 

> we close issues #50, #92, #145 with the principle that, whenever we can, we use ordered list only. Exceptions should be subjects of specific issues.' at telco 2016-02-12.

See: http://www.w3.org/2016/02/12-annotation-irc#T16-54-02
