### ISSUE TITLE
0-1 or 0-n string bodies

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#150]
From #79, there was no consensus around how many strings could be used as the body of an Annotation.  The current WD has 0-1, but there was unresolved discussion as to whether there should be an array of strings.

My proposal is close wontfix (e.g. use the current 0-1) -- the advantage of the string body is that it has a completely flat structure with no sub-resources (objects) or lists (arrays).  By introducing complexity in the simplest case, we reduce the simplicity and thereby the benefit of allowing this pattern at all.

**Comment by iherman** [comment]
At the moment, there is a discrepancy. For `body` the text says 

> There SHOULD be 1 or more body relationships associated with an Annotation but there MAY be 0.

whereas for `bodyText`, it says:

> There MAY be exactly 1 bodyText for an Annotation, 

The only argument I have seen in favour of this restriction on `bodyText` is simplicity. However, due to the possibilities for `body`, implementations already have to deal with the duality of array vs. single object when handling the bodies, so this handling can easily be transferred for multiple `bodyText`, too. In other words, the restrictions seems to be fairly arbitrary to me.

It is not a major issue because I do not believe there will be tons of annotations with multiple textual bodies. Ie, if the majority wants to keep the restriction, I will not lie down on the road:-). But spec wise it looks fairly asymmetric to me.

**Comment by hugomanguinhas** [comment]
Hi both,

A bit side question, what happens to the oa:hasBody, will it still be possible to have both text (Literal) or a Resource?

**Comment by iherman** [comment]
Decision on telco, 2016-02-19: keep to 0-1

See http://www.w3.org/2016/02/19-annotation-irc#T16-34-51

**Comment by akuckartz** [comment]
For the record: I think this restriction is arbitrary.

**Comment by azaroth42** [comment]
It is intentionally arbitrary to encourage people who think they need this functionality to actually use the TextualBody approach :)
