### ISSUE TITLE
Deref of namespace should go to vocab?

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#199]
When the namespace URI is dereferenced requesting HTML, should the response be:
- redirect to /TR/annotation-vocab/
- an interstitial landing page with links to vocab and machine readable files
- the turtle, regardless

I'm in favor of redirecting to the vocab doc, and Stian's current PR that adds the links to machine readable versions.

**Comment by iherman** [comment]
@azaroth42, I am afraid the first option (redirect to the TR document) is not really consistent with the license setup. By now we know that the vocabularies, ie, the turtle and other serialization files, are under a software license, whereas the vocab Recommendation will be under the document license. I think it would not really look good if, depending on the HTTP preference, one would get documents with different licenses. Let us also not forget that content negotiation means that you would get, essentially, _the same_ document albeit with the possibility of different formats. The Rec includes a number of additional facts, examples, maybe restrictions that are not expressed in the vocabulary document proper. Bottom line: I do not believe the first option is appropriate.

I do not know whether it is possible, with some tools, to produce a simple HTML file, that does only includes the vocabulary, hopefully/possibly with RDFa so that the RDF vocabulary can be extracted by and RDFa tool. If such a tool is around, we should use it to produce a simple HTML file. Otherwise there is no HTML version, and conneg can be used to choose among Turtle, JSON-LD and, for the old-skool users, RDF/XML. The vocabulary file itself should include (it may already have it, have not yet checked) a reference to the /TR document as a seeAlso or something similar.

**Comment by stain** [comment]
OK, I think I agree with @iherman that due to the licensing differences we should no do a redirect straight to the spec.

However do I understand you right @iherman that you don't want a a full listing as [with LODE](http://www.essepuntato.it/lode/owlapi/https://rawgit.com/stain/web-annotation/updating/vocab/wd/oa.ttl) or [Widoco](https://cdn.rawgit.com/stain/web-annotation/cb67ce387c031f02afe44ecdfbbfc7670d534afe/vocabulary/wd/oa.html) ?

For the current https://www.w3.org/ns/oa.html we used LODE and hand-edited the top.

**Comment by stain** [comment]
Each `oa:` term will have a corresponding section in the TR html, so how about a very simple listing as on http://pav-ontology.github.io/pav/pav.rdf (but without using XSLT!) with hyperlinks? E.g.

> `https://www.w3.org/ns/oa#TextualBody`
> Textual Body
> See http://www.w3.org/TR/annotation-vocab/#textualbody

**Comment by iherman** [comment]
> On 30 Mar 2016, at 10:36, Stian Soiland-Reyes notifications@github.com wrote:
> 
> OK, I think I agree with @iherman https://github.com/iherman that due to the licensing differences we should no do a redirect straight to the spec.
> 
> However do I understand you right @iherman https://github.com/iherman that you don't want a a full listing as with LODE http://www.essepuntato.it/lode/owlapi/https://rawgit.com/stain/web-annotation/updating/vocab/wd/oa.ttl or Widoco https://cdn.rawgit.com/stain/web-annotation/cb67ce387c031f02afe44ecdfbbfc7670d534afe/vocabulary/wd/oa.html ?
> 
> For the current https://www.w3.org/ns/oa.html https://www.w3.org/ns/oa.html we used LODE and hand-edited the top.

As far as I can see, the information in oa.html (ie, the RDF that I can extract) is identical to the turtle content, right? I think that is fine. 

(Minor issue: I do not know the details of the tool, but it would be good if it did not generate @xmlns:XXX for the prefixes but used @prefix instead. the usage @xmlns:XXX is deprecated in RDFa 1.1…)

**Comment by stain** [comment]
OK, then I've added an `oa.html` now to #188 pull request.  I added an RDFa conversion of `oa.ttl` at the end - I am afraid I had to save it from Firefox as a "complete webpage" to avoid the javascript loading of `section/*.html` - and to hand-add the RDFa.

See http://stain.github.io/web-annotation/vocab/wd/oa.html 

It seems to not have any `xmlns:xxx` stuff in it :)

**Comment by azaroth42** [comment]
Given the license concern, I think it would be best to have an interstitial HTML page that lists the various representations of the ontology (Turtle, JSON-LD, RDF/XML), and has a link to annotation-vocab.

**Comment by iherman** [comment]
Just to be clear about what you say, @azaroth42 : have an HTML file with RDFa, plus the Turtle, JSON-LD, and RDF/XML, all with identical RDF content, all having the same license and referring to the /TR document. I guess that would be as complete as it gets!

**Comment by azaroth42** [comment]
Okay to have interstitial, if possible to have RDFa in the document then we should.

**Comment by azaroth42** [comment]
ACTION: Verify the behavior of AppSpot translation with respect to namespaces and contexts, and potential confusion of the two

**Comment by azaroth42** [comment]
ACTION:  Verify https mixed content model interactions if context document is imported from https into an http document

**Comment by azaroth42** [comment]
@nickstenning says it's no problem -- but the other way around would be.  HTTPS importing HTTP would  not work, but HTTP importing HTTPS is okay.  So decision to use HTTPS for the namespace and context document.

**Comment by iherman** [comment]
Discussed at F2F meeting 17.05.2016, 
- Use intersitial HTML document, with RDFa of the vocab if possible, http://www.w3.org/2016/05/17-annotation-irc#T13-05-17-1
- Use https for the namespace and context documents, not http, http://www.w3.org/2016/05/17-annotation-irc#T13-06-03

**Comment by BigBlueHat** [comment]
@azaroth42 I believe you said to hold off on this one, so I'm unassigning it to make that clear. Hope that's :cool:.
