### ISSUE TITLE
Annotation protocol available or not?

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#20]
If the annotation protocol is not mandatory to support along with the model, how can a client determine whether then protocol is supported?  If it is not supported, is there a way to describe or at least identify the service that /is/ available?

The protocol can advertise itself, via an HTTP header for example, but that doesn't help with other protocols.  Should determine the scope of the interaction between the model and arbitrary protocols, and how our protocol can identify itself.

**Comment by tilgovi** [comment]
Content negotiation and discovery. Find link (TBD), request, get an intelligible service descriptor.

**Comment by stain** [comment]
The model can of course be used in any context, for instance we already use [OA inside a ZIP file](https://w3id.org/bundle/#manifest-annotations). The ZIP file does not respond to any annotation protocol.

I have already suggested the `Link` header, which I think is a sensible way to go from a given document/resource to its preferred annotation endpoint - but an application could also have its own favourite/configured annotation endpoint, for instance if you work for a pharmaceutical company you would store all annotations on an in-house server. This can still use the Annotation protocol in order to use the same client libraries etc.

**Comment by raydAtLC** [comment]
Why not make the annotation protocol mandatory, with the lowest level of support being the capability to indicate that you don’t support any other capability.

**Comment by azaroth42** [comment]
No love, closing issue :)
