### ISSUE TITLE
 'generated' and 'modified' should use UTC by default

### ISSUE THREAD

**Issue by r12a** [w3c/web-annotation#216]
[Raised by Addison Phillips
not yet discussed by the i18n WG]

The "time zone" defined by xsd:dateTime and by ISO 8601 is not actually a time zone but is instead a UTC offset. There are numerous problems with using UTC offsets as if they were time zones when it comes to time presentation later. Ultimately, since the value being described is actually an incremental time acting as a timestamp (more on that terminology in a moment), there should be language that defines UTC as the default when timezone (offset) information is not provided.

Note that the term "incremental time" is defined by [https://www.w3.org/TR/timezone/]. The goal here is to produce timestamps rather than floating time values and to make the time stamps convertable with incremental time. When information such as time zone (offset) or the time of day are omitted, the conversion between the serialized format and incremental time values should be assumed to be the "zeroing out" of the field and the normalization of the value to UTC-based epoch dates. That should be cited for implementers.

**Comment by iherman** [comment]
Same as #215, resolution there is relevant, but...

**Comment by iherman** [comment]
... that requires to:

RESOLUTION: Revert to requiring xsd:dateTime, and to REQUIRE UTC for all timestamps

See: http://www.w3.org/2016/05/17-annotation-irc#T15-17-37

**Comment by nickstenning** [comment]
I'm not sure all of the context is clear from the IRC log. 

The feedback from Addison (as we understood it) was that the use of these fields as timestamps -- that is, referring to an unambiguous point in time -- as well as the fact that they are assumed to be machine generated, means that interoperability is best served by ensuring a default of UTC.

A discussion within the WG was that taking this to its logical conclusion, we should simply require all timestamps to be UTC. Mapping these timestamps to users' local timezones is a display issue.

**Comment by aphillips** [comment]
@iherman No, I'm not suggesting that you `require UTC`. I'm pointing out that timestamps all map to (UTC-based) epoch times. That is, these are the same:

   2016-05-18T00:00:00Z
   2016-05-18T08:00:00+08:00

But it should be noted that +08:00 is not a time zone and the above is not obvious.

And actually, timestamps aren't the problem. The problem is with floating time values. For example, in a few places in the document you refer to specific date versions of a resource (the example I use in my day job would be a specific Sunday New York Times edition). The date of that resource should not be effected by the local time zone on display. If timestamps are permitted for floating time values (which you might want to avoid creating in the first place), then you'll have problems with the date changing for people with different local times.

**Comment by iherman** [comment]
Does the xsd dateTime allow for the specification of floating time stamps? Because if not, I am not sure we can express this.

I obviously understand the importance of a floating time (I use it frequently in my calendar) but I am not sure it is so important for the timestamp of an annotation (which is, after all, used for time-stamping a specific annotation for comparison). In other words, I am not sure I see the use case for floating time in this particular case.

The fact of requiring UTC is again for an easier processing by machines. These time stamps are mostly created by machines, ie, whether it is in UTC or something else does not make too much difference. But makes _processing_ such timestamps easier...
