### ISSUE TITLE
Normalisation of Text Quote Selector

### ISSUE THREAD

**Issue by r12a** [w3c/web-annotation#222]
[raised by r12a, not yet discussed by the i18n WG]

4.2.4 Text Quote Selector
https://www.w3.org/TR/2016/WD-annotation-model-20160331/#text-quote-selector

> The text MUST be normalized before recording. Thus HTML/XML tags should be removed, character entities should be replaced with the character that they encode, unnecessary whitespace should be normalized, character encoding should be turned into UTF-8, and so forth. The normalization routine may be performed automatically by a browser, and other applications should implement the DOM String Comparisons method. This allows the Selector to be used with different encodings and user agents and still have the same semantics and utility. 

I think we agreed on the teleconference that normalization is not appropriate before establishing a range using the Text Position Selector (counting characters), but it **is** appropriate for the Text Quote Selector (which selects a string with prefix and suffix), since the basis for identifying that location relies on matching strings.  I just want to be sure that that's correct, and if so that the reference to [DOM String Comparisons](https://www.w3.org/TR/2016/WD-annotation-model-20160331/#bib-DOM-Level-3-Core) serves the expected purpose.

**Comment by nickstenning** [comment]
Discussed at F2F meeting 2016-05-17.

We established, I think, that this concern is fundamentally about annotation clients _modifying_ the normalisation of the underlying document, because document editors may have valid reasons for wanting to preserve a particular unicode normalisation in their document (@r12a gave the example of his International Phonetic Alphabet editor).

Perhaps there is an editor action here to add a note to the spec suggesting or requiring the annotation clients do _not_ modify the normalisation of the annotated document. If we decide they need to (for example) compute TextPositionSelector indices in terms of the fully-composed normalisation of the document, that should be done _without_ modifying the document.
