### ISSUE TITLE
Model Typos

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#254]
- [x] affect -> effect in 1.3.1
- [x] SHOULD -> MUST for IRI of Annotation? in 3.1
- [x] type of the Body resource --> type of the Body or Target resource  in 3.2.2
- [x] too many "and"s in intro of 3.2.4
- [x] Description of use case and example do not match in 3.2.4
- [x] Choice lacks id and type in the model table  (MAY and MUST respectively) (3.2.7)
- [x] ... as do Composite, List and Independents (3.2.8)
- [x] `.`s at the end of table lines, especially bad in 3.3.2
- [x] 3.3.3 intro doesn't say what the roles or properties are used for
- [x] support -> supports in 3.3.4
- [x] delete "that" from classifying in 3.3.5
- [x] them -> it in describing in 3.3.5
- [x] Add cc-zero to example in 3.3.6
- [x] maintaining -> maintains in 3.3.7
- [x] core data model -> section 3 in 4.0
- [x] one or more label -> labels in 5.1
- [x] The TimeState should refine the Request State in the Complete Example
- [x] Manu Sporny in acks
- [x] Charmod should be normative ref

**Comment by iherman** [comment]
I accepted the pull request. 

My only, extremely and absolutely minor comment: you have a changed an example to use the French text "je l'aime!'. I presume you translated the English expression for "I love it!", to represent a comment one would make on the text. The problem is that, though it is the literal translation, it does sound funny in French in this respect; "je l'aime" is really used for persons only... If you look for an analogy of "I love it!", then, I suppose, the French expression "j'adore!" is more appropriate. If you want to be ruthlessly precise, actually, it should be "j'adore !", because the crazy typesetting rules in French require a space between the text and the '!' sign...

**Comment by rtroncy** [comment]
I second! It should be "j'adore !" ... with a proper white space before the exclamation mark, and this is not a crazy typesetting rule :-)
