### ISSUE TITLE
Create SVG versions of diagrams

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#286]
Either by export from Omnigraffle, or via https://github.com/ccnmtl/graffle2svg

**Comment by iherman** [comment]
I do not know Omnigraffle, but we should be careful to create _scalable_ SVG. This means that the header should not include an explicit width and height, only viewBox.

I am also wondering how efficient todays' browsers are in including a dozen or more SVG files. I remember having had a document with SVG diagrams in the past (RDFa Primer) and it was soooo slow to load that I had to give up. But many years have gone by since then.

**Comment by iherman** [comment]
Running out of time, close this issue without further actions
