### ISSUE TITLE
Should the fragment specification URLs be https?

### ISSUE THREAD

**Issue by csarven** [w3c/web-annotation#296]
At the moment, the RFCs with http redirects to https. The question is whether the data model should use http or https. Does it matter?

**Comment by iherman** [comment]
> On 9 Jun 2016, at 19:55, Sarven Capadisli notifications@github.com wrote:
> 
> At the moment, the RFCs with http redirects to https. The question is whether the data model should use http or https. Does it matter?

Basically, it does not. Furthermore, the references are automatically generated by respec, meaning that this is consistent with other W3C documents.

If you are fine with this, could you close the issue, please?

**Comment by csarven** [comment]
Just to be clear: I'm talking about the list of URLs in the second table here: http://w3c.github.io/web-annotation/model/wd2/#model-19 which uses `http`. The bibliography uses `https`.

I'm fine other way, but I would suggest uniformity by using https URLs in the table. I can create a PR if that's desirable.

**Comment by iherman** [comment]
Ah, sorry. Yes, this should be consistent with what is in the bibliography.

@azaroth42?

**Comment by azaroth42** [comment]
We don't control the bibliography of course, it's imported via respec. Also note that we refer to the plain text RFC, and the bibliography goes to the HTML rendering.

That said ... when you dereference the URLs in the table you get redirected to the HTTPS scheme. I'm not sure that it matters overly, but I'm happy to change them to https if that's considered editorial.

**Comment by csarven** [comment]
I think it is a minor editorial change, but leave it up to you.

If it matters, I'll use `https` in my implementation. Other implementations will do one or the other. Some will copy/paste what they see directly from this spec. So, that may be the main thing to consider here. Will our implementations be smart enough to equate http and https  because we went ahead it differently?

**Comment by azaroth42** [comment]
On reflection, I think this is a normative change. Implementations would need to change their behavior to look for https:// rather than http://.  This would affect all existing clients, as the conformsTo list was also part of the CG work, and the entries haven't changed.

As the use of the URIs is just as identifiers, and they redirect to HTTPS, I would suggest following the specification and using HTTP like the spec suggests. Otherwise you're creating interoperability problems for no reason.

Given we're in feature freeze, I'm tagging `wontfix`. Sorry!
