### ISSUE TITLE
Requirements for Agents

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#349]
There are no MUSTs for agents, because we don't want to mandate that agents have URIs (e.g. they can be blank nodes with properties) and we don't want to mandate any particular property (e.g. they might have a name or an account handle).  However that means that, according to the specification, the following should be legal:

```
{
  "type": "Annotation",
  "target": "http://example.org/target",
  "creator": {}
}
```

Which I'm not sure is even legal JSON-LD, as it would be a blank node with no predicates associated with it.  So it seems like we need one clarifying requirement that there MUST be at least one property associated with an agent?

**Comment by iherman** [comment]
I would expect the JSON-LD to be legal; after all, though fairly meaningless, the following triple is legal in RDF:

```
<something> ex:prop [].
```

I am not sure we should add a MUST at this place. Yes, authors can create meaningless annotations or meaningless statements about annotation. So what? We cannot check them all...

**Comment by tcole3** [comment]
I had already written a schema to check for presence of generator (and similar one for creator) that is perfectly happy with an empty object as value for generator. In part, the schema looks like (basically the value of moderator is either a string of format uri or an object, empty or otherwise, or an array comprised of these values:

```
        "properties": {"generator":  
          {"oneOf": [
            { "$ref": "id.json#/definitions/stringUri" },
            { "type": "object" },
            {
                "type": "array",
                "minItems": 1,
                "items": 
                { "oneOf": [
                    { "$ref": "id.json#/definitions/stringUri" },
                    { "type": "object" }
                  ]
                }
            }
         ]
       }
      }
```

Separately I have schemas that check for single creator (a should) and for each property of agent that we allow in the model, but these are clearly indicated as optional -- either may or should. So I think the model is okay as is in terms of being able to validate and track implementation. And I tend to agree with Ivan that in this instance we do not need or want to dictate descriptions of agent beyond our existing shoulds and mays. A must is not needed here since it would be hard to pick the single Agent property we think essential, assuming as you say that it should not be id.

**Comment by BigBlueHat** [comment]
Here are the N-Quads the [JSON-LD Playground](http://json-ld.org/playground/#startTab=tab-nquads&json-ld=%7B%22%40context%22%3A%22http%3A%2F%2Fwww.w3.org%2Fns%2Fanno.jsonld%22%2C%22type%22%3A%22Annotation%22%2C%22target%22%3A%22http%3A%2F%2Fexample.org%2Ftarget%22%2C%22creator%22%3A%7B%7D%7D&context=%7B%7D) generates:

``` turtle
_:b0 <http://purl.org/dc/terms/creator> _:b1 .
_:b0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/oa#Annotation> .
_:b0 <http://www.w3.org/ns/oa#hasTarget> <http://example.org/target> .
```

References `_:b1` as a blank node...but then there's no node.

**Comment by iherman** [comment]
> On 19 Aug 2016, at 17:11, BigBlueHat notifications@github.com wrote:
> 
> Here are the N-Quads the JSON-LD Playground generates:
> 
> _:b0 http://purl.org/dc/terms/creator _:b1 .
> _:b0 http://www.w3.org/1999/02/22-rdf-syntax-ns#type http://www.w3.org/ns/oa#Annotation .
> _:b0 http://www.w3.org/ns/oa#hasTarget http://example.org/target .
> References _:b1 as a blank node...but then there's no node.

To be very precise, there is a node (referred to by _:b1) but we do not know anything about it. A blank node may be considered as an existential quantifier in the logic sense..

**Comment by azaroth42** [comment]
Happy to have no change, just wanted to raise it for discussion :)
