### ISSUE TITLE
Collection vs Annotation Page

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#376]
(storing this in github for easier tracking)

> Dear all,
>
> I was going through both the WA protocol (Section 4.3) and model (Section 5.2, Appendix E) specs, and noticed an inconsistency that appears to be a typo (but not really sure) between the text and title document and some examples with regards to AnnotationPage and CollectionPage. Is there a difference between them or should the CollectionPage be renamed to AnnotationPage (or the other way around)?
>
> About the Section 4.3 of the protocol, since many of the properties of the AnnotationPage are mentioned, I was wondering that it would be nice to mention the "startIndex" as well, since it may be easily overlooked.
>
> Thanks in advance!
>
> Best regards, Hugo
>
> Hugo Manguinhas Technical R&D Coordinator
>
> T: +31 (0)70 314 0998 M: E: hugo.manguinhas@europeana.eu Skype: hugo.manguinhas

**Comment by azaroth42** [comment]
AnnotationPage is the name used in the JSON-LD context for the class `as:OrderedCollectionPage` (per the context in -vocab appendix A).  Which is why the protocol document gets a little bit twisty with names.  I'll make it consistently AnnotationPage, with a reference to Vocab to explain.

And +1 on the reference to startIndex.

Thanks Hugo!
