### ISSUE TITLE
Ontologies use non-existant owl:previousVersionURI

### ISSUE THREAD

**Issue by gkellogg** [w3c/web-annotation#381]
The closest I can find in OWL is `owl:versionIRI`. Perhaps this can be done with PROV, if it's important.

**Comment by azaroth42** [comment]
Huh. I just copied it from Stian's original one.  Happy to drop it.

**Comment by iherman** [comment]
I have found two alternatives in prov:

1. https://www.w3.org/TR/2013/REC-prov-o-20130430/#wasDerivedFrom
2. https://www.w3.org/TR/2013/REC-prov-o-20130430/#wasRevisionOf

I think the second matches our intentions. I have prepared a pull request (#385) to settle this. @azaroth42, I hope I changed the right files, I did not want to run the scripts because I was not sure they are indeed the right ones. Please check and merge the PR if you agree (it should also close this current issue I believe; if not, should be done manually). 

Cc: @gkellogg
