### ISSUE TITLE
Support for Notification

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#49]
The protocol should support notification of activity within the annotation ecosystem, such as sending a notification to subscribers when an annotation is created on a resource that is being monitored.

This is a high level tracker issue but involves at least the following steps:
- [ ] Identify and describe use cases
- [ ] Identify or design appropriate notification model, with features that fulfill the use cases
- [ ] Identify or design appropriate transport mechanism for the model
- [ ] Document
- [ ] Test

**Comment by azaroth42** [comment]
Proposal: 
Review WebMention as a very simple notification platform that the SocialWeb WG are looking to take through CR:  http://webmention.net/  If we think it has legs, great.  If not, we should discuss whether we think there's anything we can accomplish before the end of the charter.

**Comment by iherman** [comment]
Before going into the review of the WebMention spec, I would like to understand the use cases for annotation. In particular, is there any user aspect that either WebMention or Pingback does not cover and, as a consequence, we have to pick it up as a work item at all (as opposed to just let annotation services pick their own solution at their heart's content).

(To be clear, I have looked at the WebMention spec itself and, as you formulate, it does have legs, the question is whether we have to care about those legs in the first place!)

**Comment by csarven** [comment]
Going to leave this here for now: [Solid's ripples/pingback](https://github.com/solid/solid-spec/blob/master/ripples.md) and hope to come back to it later. Please note that it is very much a draft until we gain more implementation experience. It may or may not stick around Solid. We are trying to see if/how it overlaps with Solid's idea of an "inbox". The most I can say about ripples/pingback for now is that, I have an early version working in [dokieli](https://github.com/linkeddata/dokieli) for Web Annotations. LDP, RDF etc friendly.

I would suggest steering away from Webmention since it is rather stuck on an archaic view of data on the Web.

**Comment by iherman** [comment]
Well... being an outsider of these things, but looking at the comment of @csarven, this seems to suggest that the whole area of pingback (or whatever the modern name for it is) is still in flux. If so, I would suggest not to do anything in this area for annotations (pushing it, possibly, into a second version of the spec(s), ie, when things become more stable. It is not the job of this working group to sort this out...

**Comment by gobengo** [comment]
If Federated Annotation is out of scope of this WG, then ignore Webmention (and Solid/Ripples). But if it is in scope, and you want the simplest thing out there (just an 'FYI you were mentioned at this URI'), then it's a pretty good building block.

Federation is only mentioned in the Annotation WG charter as

> Social Web Working Group
>    For coordination on the Social API and the Federation Protocol (to be developed by the Social Web Working Group) and the HTTP API to be developed for annotation.

The following needs a link to be substantiated:

> I would suggest steering away from Webmention since it is rather stuck on an archaic view of data on the Web.

**Comment by azaroth42** [comment]
I think it's in scope as an HTTP API that advances the state of annotation interoperability between disparate systems.  It features heavily in Doug's ecosystem diagram, for example.  That said, on the 12/16 call we can decide.

**Comment by csarven** [comment]
@gobengo re: "simplest thing out there (just an 'FYI you were mentioned at this URI')" - So, that's nothing more than an HTTP POST with two parameters to a reserved endpoint somewhere. Are you suggesting that's spec or discussion worthy in this day and age?

Let me put it this way, if simplicity was the only concern here, we only need to make a POST to an URL (e.g., an article which accepts notifications, i.e., POSTs) with a single parameter; source HTTP URI. That doesn't even introduce the extra step to discover the endpoint. If simplicity is truly what you are really after, there you have it.

Webmention neither gives you a simple nor a precise mechanism to make notifications. It isn't precise simply because it offloads the work to the implementer to figure out which claim(s) there may be and or actually intended for the receiver. It doesn't include the `property` parameter. That causes unnecessary imperative programming with non-interoperable internal logic per implementation. It would be better handled by taking the declarative approach when submitting notifications, i.e., tell exactly the source, property, target to the receiver about the claim so that it can also verify it easily. That "triple" so to speak, is part of the core data, and not some "extension" (which is a completely flawed understanding of data). I've discussed this in sufficient detail elsewhere. Please read http://csarven.ca/webmention or review Webmention issue 1 again.

In the case of Web Annotation, something like this (among many other possibilities) is what we'd like: "An annotation of a specific kind/role/motivation.. was made to this media fragment by someone on this date, with this license.. ". Webmention doesn't give you that by any stretch of the imagination.

**Comment by csarven** [comment]
@azaroth42 I agree that notifications are in scope (not to mention that, we can already purpose LDP exactly for this). Solid extends LDP where applicable. I propose Solid/Ripples as a possibility, but like I said, it needs to iron out some stuff e.g., vocabulary. If the Web Annotation WG wants to investigate further, that'd be great.

I also agree with @iherman that if this is at all stretching a bit far (given the state of things), it is better to leave out notifications for now.

My preference is to pursue this further b/c I see where LDP/Web Annotation/Ripples fit together. cc @BigBlueHat

**Comment by rhiaro** [comment]
I think webmention has the potential to develop in a direction that could be useful to Annotations. (I also optimistically think it has the potential to be compatible with solid/ripples, work in progress). If any of you have time to check it out and give input based on what you need, the SWWG would appreciate it.

Given the Annotations data model, I can certainly see how webmention with the `property` parameter would be more valuable than without. At the SWWG f2f it was resolved that `property` would be considered an extension pending further implementations. Given enough implementations, it would be considered for the core spec. I'd love to see it in the core spec, so if this is something Annotations are interested in pursuing then +1 from me!

On the other hand, if the need here is to send even more data with the notification (rather than having the target fetch it from source) than just source+property+target, webmention is not ideal. Eg. solid/ripples would let you write arbitrary triples as the notification, rather than sending these predefined values.

**Comment by iherman** [comment]
> On 16 Dec 2015, at 23:07, Sarven Capadisli notifications@github.com wrote:
> 
> @azaroth42 https://github.com/azaroth42 I agree that notifications are in scope (not to mention that, we can already purpose LDP exactly for this). Solid extends LDP where applicable. I propose Solid/Ripples as a possibility, but like I said, it needs to iron out some stuff e.g., vocabulary. If the Web Annotation WG wants to investigate further, that'd be great.
> 
> I also agree with @iherman https://github.com/iherman that if this is at all stretching a bit far (given the state of things), it is better to leave out notifications for now.

Thank you. I believe that _at this moment_ this is the only reasonable choice for this Working Group. We have other, more annotation-specific fishes to fry.

Formally, I would propose to leave this issue open but resolution should be postponed to (late) Spring 2016. If, by then, the Social Web WG gets significantly further, we can see whether a reference to their work is doable. If not, we should close the issue then without further actions.

(In particular, I do not believe we should use telco time on this issue in the coming months.)

> My preference is to pursue this further b/c I see where LDP/Web Annotation/Ripples fit together. cc @BigBlueHat https://github.com/BigBlueHat

**Comment by csarven** [comment]
Sending more data allows at least two use cases which are prevented by the Webmention approach right from the start, but possible with Solid/ripples:
- duplicate any information if you want/need to (e.g., for a quicker verification process)
- complimentary information which do not exist at source e.g., the agent that's submitting the notification is not necessarily the creator of the source, as well as including provenance level information, or even types of UIs/typographical (e.g., annotations for marginalia) suggestions in which the source may be suitable for.

**Comment by azaroth42** [comment]
Given the timing (WebMention is only FPWD today, nothing normative from Solid/Ripples), I agree with @iherman. I propose: `postpone` due to the flux in technology. Better to delay than back the wrong horse and risk not getting anything to the finish line.

**Comment by iherman** [comment]
+1

**Comment by tilgovi** [comment]
:+1:

**Comment by iherman** [comment]
Closing the issue, being discussed at telco, 2016-01-13, see http://www.w3.org/2016/01/13-annotation-irc#T16-50-35
