### ISSUE TITLE
Should the namespace change?

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#53]
From #46, there is the question of whether the namespace should change for the model. 

Note that this is only a concern from the RDF perspective, not the preferred JSON serialization which won't have even a prefix, let alone the complete namespace (per #12).  

From the telco on 2015-07-08, some of the discussion included:
- There's a lot of use of the namespace
- Changing namespaces is generally a bad idea
- Backwards compatibility without changing the namespace is important
- The CG spec is explicitly a draft, so we need not feel too constrained by changing the definitions in a non-backwards-compatible way
- It demonstrates continuity and inclusion, rather than division and competition, hopefully avoiding splitting the community of practice
- It has the oa acronym ... which would be confusing without the history

The decision on the call was to defer the decision until later.

**Comment by jjett** [comment]
With regards to Doug's question about schema.org, IIRC it was floated that
we swap out various properties and entities reused from Dublin Core for
equivalent properties and entities that appear in schema.org. It's been
quite a number of months since it came up and I don't recall if we ever had
a consensus on whether or not that was a good idea.

---

Jacob Jett
Research Assistant
Center for Informatics Research in Science and Scholarship
The Graduate School of Library and Information Science
University of Illinois at Urbana-Champaign
501 E. Daniel Street, MC-493, Champaign, IL 61820-6211 USA
(217) 244-2164
jjett2@illinois.edu

**Comment by fhirsch** [comment]
I think we need a concrete proposal and agreement with the schema.org community to progress this approach.

**Comment by jjett** [comment]
My question is what are the implications for the DC community? This won't
be interpreted as some kind of no-confidence vote in DC, will it?

There are a lot of stakeholders; it might make sense to be agnostic and
note that we have no preference which vocab gets used as long as some form
of entity format typing, etc. is used. I know that's a complicating factor
since body content would have to be checked if its dc:text or the schema
equivalent but we're already checking for content type anyway so... in for
a penny, in for a pound?

Since the clients have to know what to do with the content anyway; it seems
like this could be left to local developers to decide.

---

Jacob Jett
Research Assistant
Center for Informatics Research in Science and Scholarship
The Graduate School of Library and Information Science
University of Illinois at Urbana-Champaign
501 E. Daniel Street, MC-493, Champaign, IL 61820-6211 USA
(217) 244-2164
jjett2@illinois.edu

**Comment by iherman** [comment]
Admin comment: I think we should spin off the issue on DC vs. schema to another issue.

**Comment by jjett** [comment]
+1

It seems completely orthogonal to the oa namespace discussion.

**Comment by azaroth42** [comment]
If #70 is accepted, I propose that we change the namespace to ns/anno# as any backwards compatibility would be gone.

**Comment by csarven** [comment]
Besides what's already mentioned in this issue and the possibility of #70 going through, are there other changes to the vocabulary which may be a good-enough reason to change the namespace?

**Comment by iherman** [comment]
> If #70 is accepted, I propose that we change the namespace to ns/anno# as any backwards compatibility would be gone.

+1 to that

**Comment by azaroth42** [comment]
Given #70 was not accepted, closing WontFix. (Being... we'll keep the same namespace)
