### ISSUE TITLE
Should we systematically use typing in the model (and in the examples)?

### ISSUE THREAD

**Issue by iherman** [w3c/web-annotation#61]
In all our examples we systematically use RDF typing for all objects, eg,

```
{
    "@id": "http://example.org/anno1",
   "@type": "Annotation",
  ....
     {
        "@id" : "http://example.org/tag1"
       "@type": "EmbeddedContent"
      ...
```

From an RDF point of view, this is not required. If the RDFS vocabulary, that should eventually be prepared, includes the necessary `rdfs:domain` and `rdfs:range` information, those who are interested can use simple RDFS reasoners to retrieve the type information. On the other hand, for pure JSON users this information seems to be superfluous and disturbing (exacerbated by the fact that `@type` is not exactly looking nice, although that may be mitigated through the `@context`).

**Comment by azaroth42** [comment]
From an RDF point of view, no. From a developer point of view, I (personally) would prefer to be told what sort of thing the object is, rather than having to guess by introspecting on the object's properties.  Especially if properties or patterns beyond those of OA are used.

For example:

```
{ "value": "paris" }  or in Turtle  [ rdf:value "paris" ]
```

EmbeddedContent? FragmentSelector? HttpRequestState? I can tell from the relationship and structure, but it's more work than just being told :)

Worse:

```
{ "start": 100, "end": 400 }
```

Could be legitimately either a TextPositionSelector or a DataPositionSelector, and the client would do different things for those two classes.
In this case I need to be told which.

```
[ "members": [1,2,3] ]
```

A oa:Choice or a oa:List?  Again, very different behavior.

Programming defensively, one would check for the properties that are absolutely required and not rely on type ... unless you have to. But it's much easier (again IMO) to do a @type value to internal class map when creating the structure in your environment.

**Comment by iherman** [comment]
It is a matter of balance. There may be cases where the type information is really important (eg, your choice vs. list), but asking to have it systematically even for obvious cases (like an annotation) makes all the data and examples look more complex than necessary. 

As far as I can see JSON programmers are pretty much used to a kind of a "top-down" approach whereby they start from an object (the annotation), look at the various properties and then they drill down to values serving as, in some cases, new objects. In other words, the program knows about the 'context' (in the loose sense of the word), ie, the type information may be ignored. That is of course different from the Linked Data vision where each triple can be seen and considered in isolation; the question is where the 80/20 cut it for our constituency...

I may be wrong in that; I guess the implementers in our midst should tell us whether the type information is indeed useful or not...

**Comment by tilgovi** [comment]
I think it's fine to have the type information. It may make the examples easier to understand, even. Remember, someone reading the spec for the first time will not be as familiar with classes. It may be a helpful reminder to be told that an object with a `source` is a `SpecificTarget`.

If we want radically simple examples for JSON we can have an informal cookbook, maybe?

**Comment by tilgovi** [comment]
We could also maybe have the examples all assume to use a context we define once and use [typed values](http://www.w3.org/TR/json-ld/#typed-values) to make a lot of the typing information in the examples unnecessary?

**Comment by azaroth42** [comment]
Closing, superceded by #67
