### ISSUE TITLE
Keeping the OA ontology up to date

### ISSUE THREAD

**Issue by csarven** [w3c/web-annotation#66]
Question: is there a workflow in place to update http://www.w3.org/ns/oa or a preference for making PRs? I'd like to be able to see the new terms that are discussed in http://www.w3.org/TR/annotation-model/

**Comment by stain** [comment]
I believe the ontology at http://www.w3.org/ns/oa.ttl etc. come directly from

https://github.com/stain/oa

and was last updated for the earlier Open Annotation Model work 

It would need to be added here for further work (I'll do that).  The trouble with editing this is the pipeline for converting to RDF/XML, JSON-LD and HTML, this was done manually earlier. I suggest just adding `oa.ttl` for now so we get consistent pull requests?

**Comment by iherman** [comment]
@stain, I have processed the pull request; it is indeed better to have it in the WG's repository. However, I presume that vocabulary is still subject to change, ie, I did not update anything in the www.w3.org/ns directory. I trust you will notify me when that extra step is to be done.

@csarven I guess you have now your answer, too: I think the proper way is to issue PR-s against the WG's repository, using @stain's structures.

Thanks to both!

**Comment by stain** [comment]
Thanks @iherman. If @csarven wants to have a crack at updating it, this would be great - I can do it, but can't quite promise when.. (don't look at yesterday's timestamps!)

**Comment by azaroth42** [comment]
Tagging postpone -- I don't think we need this to enter CR, and can make sure it's fixed once we're there.
Yes?

**Comment by iherman** [comment]
@azaroth42 not clear what postpone means in this case. I presume implementations depend on the namespace document, ie, it must be o.k. _when we enter CR_. If you mean, by postpone, wait until then, that is of course fine. But I think we do need it to enter CR.

**Comment by stain** [comment]
Agree that we need namespace doc/ontology to enter CR, obviously it would
then need to be in sync with CR specs :)

Deliverable wise, are we going for a simple HTML page as well as the
different RDF formats on content negotiation? Aka https://www.w3.org/ns/prov

Or more like a specification on its own, like https://www.w3.org/TR/prov-o/
?

**Comment by iherman** [comment]
OA is currently installed in HTML, TTL, JSON-LD, and RDF/XML, and content negotiation has also been set up in /ns. As far as I can see, the HTML is not marked up with RDFa, ideally it should (but not a requirement). 

I think we should simply update those.

Ivan

**Comment by azaroth42** [comment]
Okay :) Removed postpone.

**Comment by stain** [comment]
@iherman:

There seems to be problems with the content negotiation on http://www.w3.org/ns/oa now - in that it is no longer possible in a browser to follow the links to the [rdf](https://www.w3.org/ns/oa/oa.owl), [turtle](https://www.w3.org/ns/oa/oa.ttl) or [json-ld](https://www.w3.org/ns/oa/oa.jsonld) variants.

**Comment by stain** [comment]
@iherman what license should the updated OA vocabulary/ontology file have?

It came up as a [problem for Apache Software Foundation](https://issues.apache.org/jira/browse/TAVERNA-927) - as it is unclear if ontologies and schemas are 'documents' (and thus should follow the non-permissive [W3C Document license](https://www.w3.org/Consortium/Legal/2015/doc-license) - or 'software' (and thus should folow the permissive [W3C Software license](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document)

It is a problem because we tried to [include the OA vocabulary](https://github.com/apache/incubator-taverna-language/blob/master/taverna-robundle/src/main/resources/ontologies/oa.rdf) in Apache Taverna's source code - but it is [against ASF policy](http://www.apache.org/legal/resolved.html#no-modification) to redistribute non-modifiable source code - only 'binary form' or "download on build" is permitted. However w3c is known for applying a tar-pit for often-requested URLs - so we can't download directly from w3.org.

Personally I would hope ontologies and schemas could be under the software license - but this should be made explicit within the ontology/schemas files. Hopefully we'll get it right for the Web Annotation Model ontology!

**Comment by iherman** [comment]
I will have to ask our sys people. Note that it works with usual tools:

```
curl --header "Accept: text/turtle" --head http://www.w3.org/ns/oa
HTTP/1.1 200 OK
Date: Mon, 07 Mar 2016 05:50:06 GMT
Content-Location: oa.ttl
Vary: negotiate,accept,upgrade-insecure-requests
TCN: choice
Last-Modified: Tue, 06 May 2014 11:14:49 GMT
ETag: "a708-4f8b95b2a9c40;103-4f8b95b2a9c40"
Accept-Ranges: bytes
Content-Length: 42760
Cache-Control: max-age=21600
Expires: Mon, 07 Mar 2016 11:50:06 GMT
P3P: policyref="http://www.w3.org/2014/08/p3p.xml"
Access-Control-Allow-Origin: *
Content-Type: text/turtle; charset=utf-8
```

I presume this is related to the HTTP/HTTPS switch when it comes to browsers:

https://www.w3.org/blog/2016/01/w3-org-supporting-https-and-hsts/

**Comment by rigow** [comment]
@stain @iherman After internal discussions we agreed to release the ontology (not the Specification itself) under the W3C Software and Document license that is compatible with the requirements from Apache and the Open Software Foundation. 

If the ontology is a stand alone document, please use this statement: 

Copyright © 2016 W3C ® ( MIT , ERCIM , Keio, Beihang). W3C liability, trademark use rules apply. This Document is licensed under the W3C Software and Document license (link to https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document )

If it is a combined document with the Specification, please indicate the pointer in the copyright statement: 

Annex (XYZ) is licensed under the W3C Software and Document license (link to https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document )

**Comment by stain** [comment]
Thanks, @rigow!  I've added the Software&Doc license in #187 both for the OWL files and the JSON-LD files.

Since we have "Data Model Vocabulary" as a separate deliverable in our [charter](https://www.w3.org/annotation/charter/), would that then mean that we are going to publish a Specification - say http://www.w3.org/TR/annotation-vocab/  -which HTML then is under the regular Document license?

**Comment by stain** [comment]
https://github.com/w3c/web-annotation/pull/188 finished now - ready to be published on /ns/ in my view.
