### ISSUE TITLE
Expanded role for agents' activities

### ISSUE THREAD

**Issue by azaroth42** [w3c/web-annotation#7]
Agents might play more roles than just "annotator" or "serializer" with respect to an Annotation.  The model should allow a more complete description of the agents' activities with respect to the annotation, to ensure that an accurate provenance trail is maintained.

This issue is distinct from  #8 as this is about activities that have taken place (provenance in the PROV sense) rather than the intended audience of the annotation.

**Justification**

To be discussed.

**Proposal**

To be discussed,

**Background**

Using PROV-O completely was discussed in the CG and there wasn't a use case presented for why the full model was required.  The decision was to not require the creation of the full model, but to ensure that it could be [derived from the information given](http://www.openannotation.org/spec/core/appendices.html#ProvMapping).

**Links**
- [Tracker](http://www.w3.org/annotation/track/issues/5)

**Comment by lucmoreau** [comment]
Hi Rob

It may be premature to comment since there is no concrete proposal. I have a concern that conflating the serialised Annotation and its conceptual version may result in invalid provenance, if the serialisation event and the creation event are kept distinct (e.g. Distinct times).

See rule https://dvcs.w3.org/hg/prov/raw-file/default/model/prov-constraints.html#generation-generation-ordering

Luc

Professor Luc Moreau
Electronics and Computer Science
University of Southampton
Southampton SO17 1BJ
United Kingdom

On 7 Oct 2014, at 23:30, Rob Sanderson <notifications@github.com<mailto:notifications@github.com>> wrote:

Agents might play more roles than just "annotator" or "serializer" with respect to an Annotation. The model should allow a more complete description of the agents' activities with respect to the annotation, to ensure that an accurate provenance trail is maintained.

This issue is distinct from #8 as this is about activities that have taken place (provenance in the PROV sense) rather than the intended audience of the annotation.

Justification

To be discussed.

Proposal

To be discussed,

Background

Using PROV-O completely was discussed in the CG and there wasn't a use case presented for why the full model was required. The decision was to not require the creation of the full model, but to ensure that it could be derived from the information givenhttp://www.openannotation.org/spec/core/appendices.html#ProvMapping.

Links
-   Trackerhttp://www.w3.org/annotation/track/issues/5

—
Reply to this email directly or view it on GitHubhttps://github.com/w3c/web-annotation/issues/7.

{"@context":"http://schema.org","@type":"EmailMessage","description":"View this Issue on GitHub","action":{"@type":"ViewAction","url":"https://github.com/w3c/web-annotation/issues/7","name":"View Issue"}}

**Comment by azaroth42** [comment]
Hi Luc,

That is a good issue, and one that we noted in the draft specification here:  http://www.openannotation.org/spec/core/core.html#Provenance

I'll generate a new issue for it.

**Comment by shepazu** [comment]
If we do have multiple roles, I think we should use terms that are less jargon than "annotator" or "serializer". (Publishing terms like "author", "contributor", and "editor" spring to mind.)

**Comment by paolociccarese** [comment]
We normally use: createdBy, curatedBy, authoredBy and contributedBy from
(PAV - http://purl.org/pav/ ).
Where:
- creator is the agent that created the artifact
- author is the agent that created the annotation (it could be somebody
  other than the creator)
- curator is the agent that helped in shaping the annotation starting from
  content that has been authored by somebody else (for example somebody that
  interpreted a marginalia authored by someone else).
- contributor is a more loose way of keeping track of those that
  contributed bit and pieces

All the above can be also specified in a more detailed way through PROV-O
with a few more triples.

I also use publisher from Dublin Core Terms.

On Mon, Oct 13, 2014 at 5:30 PM, Doug Schepers notifications@github.com
wrote:

> If we do have multiple roles, I think we should use terms that are less
> jargon than "annotator" or "serializer". (Publishing terms like "author",
> "contributor", and "editor" spring to mind.)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/web-annotation/issues/7#issuecomment-58957857.

## 

Dr. Paolo Ciccarese
Assistant Professor of Neurology, Harvard Medical School
Assistant in Neuroscience, Massachusetts General Hospital
Senior Information Scientist, MGH Biomedical Informatics Core

CONFIDENTIALITY NOTICE: This message is intended only for the addressee(s),
may contain information that is considered
to be sensitive or confidential and may not be forwarded or disclosed to
any other party without the permission of the sender.
If you have received this message in error, please notify the sender
immediately.

**Comment by azaroth42** [comment]
Keep in mind that the Annotation and the Bodies have separate properties.  The author of an annotation is not necessarily the author of any of the bodies.  Hence the very specific terminology in the CG specification.

**Comment by paolociccarese** [comment]
Just for clarity, I am assuming you can use something like pav:authoredBy
(or the equivalent in PROVO) on any entity: Annotation, Body or Target.

For instance if I encode an existing annotation created by an expert E on a
document authored by scientist S:

<anno1> a oa:Annotation;
curatedBy <me> (or annotatedBy)
hasBody <body1> ;
hasTarget <target1> .

<body1> authoredBy <expertE>

<target1> authoredBy <scientistS>

I am using curatedBy as, in this case,  I am not really authoring the
annotation, I am more curating an existing one.
I agree that using annotatedBy is a little easier as it would not require
to define the contribution... sometimes it is hard to distinguish 'author'
vs. 'curator'.

Each other piece as its own author(s) or other provenance data.

On Wed, Oct 15, 2014 at 3:24 PM, Rob Sanderson notifications@github.com
wrote:

> Keep in mind that the Annotation and the Bodies have separate properties.
> The author of an annotation is not necessarily the author of any of the
> bodies. Hence the very specific terminology in the CG specification.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/web-annotation/issues/7#issuecomment-59261169.

## 

Dr. Paolo Ciccarese
Assistant Professor of Neurology, Harvard Medical School
Assistant in Neuroscience, Massachusetts General Hospital
Senior Information Scientist, MGH Biomedical Informatics Core

CONFIDENTIALITY NOTICE: This message is intended only for the addressee(s),
may contain information that is considered
to be sensitive or confidential and may not be forwarded or disclosed to
any other party without the permission of the sender.
If you have received this message in error, please notify the sender
immediately.

**Comment by azaroth42** [comment]
I guess the question is:  Should the data model specify more roles, or should that be left to extensions.  

My preference is just for creator/annotator as recommended, and generating software as optional, then leave everything else to further communities to define as needed.  Beyond curated, I haven't heard any further roles suggested?

**Comment by paolociccarese** [comment]
You could technically have a more complex workflow with more roles involved
(curatedBy, reviewedBy, approvedBy...).

But I believe those are not the norm and they depend on the use cases and
communities. So I agree with you to delegating that aspect to the
communities.

I recall somebody on the call bringing up the importance of roles... many
weeks ago.
But I cannot remember who she was.

On Thu, Apr 9, 2015 at 11:49 AM, Rob Sanderson notifications@github.com
wrote:

> I guess the question is: Should the data model specify more roles, or
> should that be left to extensions.
> 
> My preference is just for creator/annotator as recommended, and generating
> software as optional, then leave everything else to further communities to
> define as needed. Beyond curated, I haven't heard any further roles
> suggested?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/web-annotation/issues/7#issuecomment-91269506.

## 

Dr. Paolo Ciccarese
ORCID: http://orcid.org/0000-0002-5156-2703

**Comment by jjett** [comment]
+1. Is there a way to propose that we move forward with the roles in hand,
creator/annotator (required) and generatedBy (optional) and leave a note
somewhere (in the spec or elsewhere) that our decision doesn't preclude the
extension of the model with additional roles as determined on a community
by community basis?

That way we can mark this issue as resolved.

Regards,

Jacob

**Comment by azaroth42** [comment]
+1 to closing.

**Comment by azaroth42** [comment]
Closing without prejudice.
