### ISSUE TITLE
Simplifying hasBody

### ISSUE THREAD

**Issue by csarven** [w3c/web-annotation#79]
My impression of `hasBody` and language handling as a user/publisher:

As it is expected to work right now, `hasBody` is overloaded:
1. there is a split for completely different textual bodies; embedded and simple.
2. both cases have too many do's and don'ts.

I'm afraid that `hasBody` (arguably) will be misused.

A simpler approach here is to acknowledge that both types of textual bodies are significantly different (if so in their functionality) such that they deserve dedicated properties. An obvious strawman proposal to consider: keep `hasBody` for embedded textual body, and have (for the sake of the argument) `hasBodyText` for simple textual body.

I realize that having two properties is not pretty at this point, but I think the trade off is that, it will be less complications for both publication and consumption.

I think this will also significantly simplify language handling, i.e., dedicated dc:language and language tags.

[Another consideration is to see whether simple textual body can be a proper subset of embedded textual body.]

Thoughts?

**Comment by azaroth42** [comment]
The issue is a conflation of model and serialization.  The desire is to have a "simple" JSON serialization, and that is driving the model rather than aiming for a coherent and consistent model, and trying to fine tune the serialization over top of it.  So we end up with overloaded properties like hasBody causing inconsistencies like being able to have a URI with a string for the target being a URI, but not for the body where a string is just a string.

We discussed two properties but, if I recall correctly, the serialization of "body": "comment" was the preferred solution.  I agree, personally, that two properties would be cleaner if we must have literal bodies at all.  Then systems that don't want to use them but instead have a clean and reliable structure can just use the embedded content pattern.

As for language, having one pattern is better than two, and you can't have both language and format on a literal.  Hence the restrictions on literal bodies to have neither, especially as in JSON-LD the structure would be _identical_ to the embedded method.

**Comment by azaroth42** [comment]
@manusporny also commented that the current approach was not intuitive, and recommended multiple properties.  This would solve the overloading of hasBody, would simplify the patterns when body is a URI/URL, and still allow the desired simple annotation of just a literal body.

To try and keep it as intuitive as possible, Benjamin and Rob propose:
- New predicate `oa:hasBodyText`, json-ld key: `text`
- Rename `oa:text` (was `rdf:value` used on EmbeddedContent) to `oa:content` to avoid overloading `rdf:value` or having two `text` keys. json-ld key: `content`

**Comment by BigBlueHat** [comment]
So...if we make this change a singular, textual body annotation could take either of these forms:

``` json
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.com/anno1",
  "text": "W3C site",
  "target": "http://w3.org/"
}
```

or...more extendable-y:

```
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "id": "http://example.com/anno1",
  "body": [{
    "content": "W3C site"
  }],
  "target": "http://w3.org/"
}
```

(if providing "space" for expansion to multiple bodies...otherwise, turn that into just a single object...not an array)

These are _not_ identical, but they encode the same data, and to the user (one would think) they would be presented identically.

Given that, a developer will need to:
- check for `text` on `body`
- check if `body` is an array
- if `body` is an object, extract `content`
- if `body` is an array, loop through multiple bodies...do the right thing with each

From a graph developers perspective, there my now be a `oa:hasBodyText` string or `oa:hasBody` resource.

Or at least that's my understanding of it. :smile:

**Comment by azaroth42** [comment]
I'm :+1: on that ... but to be clear, the implication is that multiple bodies MUST use the TextualBody pattern, even if you only have strings. You MUST NOT have the value of annotation.text be an array of strings.

**Comment by BigBlueHat** [comment]
@azaroth42 oof...yeah...let's not go there. `body` (and `target` etc) already being an array or object is tedious enough (though completely unavoidable, afaik...because JSON-LD). `annotation.text` (and really `text` anywhere) should be treated as a string literal always.

Can we specify as much...given that I believe JSON-LD does not?

If we do restrict JSON-LD in this way...then we MAY need our own media type (similar to AS2's "not quite JSON-LD" processing model discussions).

**Comment by azaroth42** [comment]
Sure, we can make as many restrictions as we want in our profile, so long as they're _restrictions_ on JSON-LD, not expansions.  As per comment on #30, AS2 wants to allow non JSON-LD compatible content to be valid such as GeoJSON's list of lists construction.

**Comment by azaroth42** [comment]
Regarding the proposal to change to `content`, this would align us with the use of as:content on Objects in ActivityStreams.  

Ref: https://lists.w3.org/Archives/Public/public-socialweb/2015Nov/0037.html
PR to update the definition: https://github.com/jasnell/w3c-socialwg-activitystreams/pull/244

**Comment by jjett** [comment]
Just to clarify this proposal is focused on the JSON serialization
guidelines, is that correct?

The pattern would be:

Model                     JSON key
oa:hasBody            content:
oa:hasBodyText     text:

Is that correct?

Regards,

Jacob

---

Jacob Jett
Research Assistant
Center for Informatics Research in Science and Scholarship
The Graduate School of Library and Information Science
University of Illinois at Urbana-Champaign
501 E. Daniel Street, MC-493, Champaign, IL 61820-6211 USA
(217) 244-2164
jjett2@illinois.edu

**Comment by azaroth42** [comment]
The proposal is, in more detail:
- Create a new property oa:hasBodyText with a domain of Annotation and a range of literal.
- Use `text` as the key in JSON-LD for that predicate
- Leave hasBody alone, other than reverting to a range of rdf:Resource
- Rename oa:text to oa:content, domain of oa:EmbeddedContent, range of literal
- Use `content` as the JSON-LD key for that predicate
- Continue to have a TextualBody class, which is subClassOf oa:EmbeddedContent and allows oa:hasRole (`role`)

Assert in additional restrictions and the processing model that:
- There MUST be 0-1 hasBodyText per Annotation
- Systems MAY treat annotation.text and annotation.body[0].content as equivalent

Thus these two can be treated as equivalent:

```
{
  "type": "Annotation",
  "text": "My comment",
  "target": "http://example.org/target"
}
{
  "type": "Annotation",
  "body": {
    "type": "TextualBody",
    "content": "My comment"
  },
  "target": "http://example.org/target"
}
```

**Comment by iherman** [comment]
Rob, minor point: what is the reason to restrict hasBodyText to 0 or 1?

Otherwise +1 for me.

I.

> The proposal is, in more detail:
> 
> Create a new property oa:hasBodyText with a domain of Annotation and a range of literal.
> Use text as the key in JSON-LD for that predicate
> Leave hasBody alone, other than reverting to a range of rdf:Resource
> Rename oa:text to oa:content, domain of oa:EmbeddedContent, range of literal
> Use content as the JSON-LD key for that predicate
> Continue to have a TextualBody class, which is subClassOf oa:EmbeddedContent and allows oa:hasRole (role)
> Assert in additional restrictions and the processing model that:
> 
> There MUST be 0-1 hasBodyText per Annotation
> Systems MAY treat annotation.text and annotation.body[0].content as equivalent
> Thus these two can be treated as equivalent:
> 
> {
>   "type": "Annotation",
>   "text": "My comment",
>   "target": "http://example.org/target"
> }
> {
>   "type": "Annotation",
>   "body": {
>     "type": "TextualBody",
>     "content": "My comment"
>   },
>   "target": "http://example.org/target"
> }

**Comment by azaroth42** [comment]
It was from this comment: https://github.com/w3c/web-annotation/issues/79#issuecomment-153471521 and my response to it.

The rationale I think is that we should do what we can to fulfill the simplest use case in the simplest fashion, which is one string body and one target.  Multiple bodies quickly gets us beyond that simple case, and adds additional processing requirements to the point that it would be easier to have objects in an array in body (IMO).

**Comment by iherman** [comment]
> On 5 Nov 2015, at 18:37, Rob Sanderson notifications@github.com wrote:
> 
> It was from this comment: #79 (comment) https://github.com/w3c/web-annotation/issues/79#issuecomment-153471521 and my response to it.
> 
> The rationale I think is that we should do what we can to fulfill the simplest use case in the simplest fashion, which is one string body and one target. Multiple bodies quickly gets us beyond that simple case, and adds additional processing requirements to the point that it would be easier to have objects in an array in body (IMO).
> 
> —

If it adds extra complication to add multiple text bodies somewhere, then I am all for restricting it. But we already have, I presume

```
{
   "body" : { ….},
   "text" : {….}
}
```

Ie, several textual bodies do not complicate things. _Unless_ we say that if we use `text`, then no multiple bodies are allowed, which is not what your proposal said...

**Comment by azaroth42** [comment]
To discuss: 0-1 bodyText (either not present or a string) or 0-many (not present, a string, or an array of strings).
Otherwise proposal is as per https://github.com/w3c/web-annotation/issues/79#issuecomment-153916209

**Comment by azaroth42** [comment]
Done: http://w3c.github.io/web-annotation/model/wd2/#string-body
Raised 0-1, 0-n question in new issue: #150
